id: P80CDD444
initial_creation_type: input
source_metadata:
  Title: Bauddhālaṅkāra-Śāstram
  Editor: '-'
  Publisher: Shri Lal Bahadur Shastri Central Sanskrit Institute
  Place of Publication: 'New Delhi:'
  Year: '1973'
  Subodhālaṅkāraḥ:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:18:20.975493'
last_modified_at: '2022-03-08T16:18:20.975504'
